#!/usr/bin/env node
/**
 * Seed Discovery Script
 *
 * Finds seeds that produce games with specific kingdom cards for reproducible testing.
 *
 * Usage:
 *   npx ts-node scripts/discover-seeds.ts --card Chapel --count 3
 *   npx ts-node scripts/discover-seeds.ts --all-cards --count 1
 *   npx ts-node scripts/discover-seeds.ts --generate-reference
 */

const { GameEngine, getKingdomCardsByEdition } = require('@principality/core');
const fs = require('fs');
const path = require('path');

type CardName = string;

interface SeedInfo {
  seed: string;
  kingdomCards: string[];
  turn1Hand: Record<string, number>;
}

interface CardSeedMap {
  [cardName: string]: SeedInfo[];
}

/**
 * Group cards in hand by name and count
 */
function groupHand(hand: readonly CardName[]): Record<string, number> {
  const grouped: Record<string, number> = {};
  for (const card of hand) {
    grouped[card] = (grouped[card] || 0) + 1;
  }
  return grouped;
}

/**
 * Find seeds that include a specific card in the kingdom
 */
function findSeedsForCard(cardName: string, count: number = 3, maxAttempts: number = 1000): SeedInfo[] {
  const results: SeedInfo[] = [];

  for (let i = 0; i < maxAttempts && results.length < count; i++) {
    const seed = `${cardName.toLowerCase()}-seed-${i}`;
    const engine = new GameEngine(seed);
    const state = engine.initializeGame(1);

    if (state.selectedKingdomCards?.includes(cardName as CardName)) {
      results.push({
        seed,
        kingdomCards: [...(state.selectedKingdomCards || [])],
        turn1Hand: groupHand(state.players[0].hand)
      });
    }
  }

  return results;
}

/**
 * Find seeds for all kingdom cards
 */
function findSeedsForAllCards(countPerCard: number = 1): CardSeedMap {
  const allKingdomCards = getKingdomCardsByEdition('2E');
  const results: CardSeedMap = {};

  console.log(`Finding seeds for ${allKingdomCards.length} cards...`);

  for (const cardName of allKingdomCards) {
    process.stdout.write(`  ${cardName}... `);
    const seeds = findSeedsForCard(cardName, countPerCard);
    results[cardName] = seeds;
    console.log(`found ${seeds.length} seed(s)`);
  }

  return results;
}

/**
 * Generate markdown reference document
 */
function generateMarkdownReference(seedMap: CardSeedMap): string {
  const lines: string[] = [
    '# Seed Reference for Reproducible Testing',
    '',
    '> Auto-generated by `scripts/discover-seeds.ts`',
    '',
    '## How Seeds Work',
    '',
    '- Any string seed produces a deterministic game',
    '- Same seed + same moves = identical game progression',
    '- Seeds affect: starting deck shuffle, kingdom card selection',
    '',
    '## Usage',
    '',
    '```bash',
    '# CLI',
    'npm run play --seed=chapel-seed-0',
    '',
    '# MCP',
    'game_session(command="new", seed="chapel-seed-0")',
    '```',
    '',
    '## Quick Reference by Card',
    '',
    '| Card | Seed | Kingdom Cards | Turn 1 Hand |',
    '|------|------|---------------|-------------|',
  ];

  // Sort cards alphabetically
  const sortedCards = Object.keys(seedMap).sort();

  for (const cardName of sortedCards) {
    const seeds = seedMap[cardName];
    if (seeds.length === 0) {
      lines.push(`| ${cardName} | _(no seed found)_ | - | - |`);
      continue;
    }

    const info = seeds[0];
    const handStr = Object.entries(info.turn1Hand)
      .map(([name, count]) => `${name}(${count})`)
      .join(', ');
    const kingdomStr = info.kingdomCards.slice(0, 5).join(', ') + '...';

    lines.push(`| ${cardName} | \`${info.seed}\` | ${kingdomStr} | ${handStr} |`);
  }

  lines.push('');
  lines.push('## Detailed Seed Information');
  lines.push('');

  for (const cardName of sortedCards) {
    const seeds = seedMap[cardName];
    if (seeds.length === 0) continue;

    lines.push(`### ${cardName}`);
    lines.push('');

    for (const info of seeds) {
      lines.push(`**Seed**: \`${info.seed}\``);
      lines.push('');
      lines.push('**Kingdom Cards**:');
      lines.push('```');
      lines.push(info.kingdomCards.join(', '));
      lines.push('```');
      lines.push('');
      lines.push('**Turn 1 Hand**:');
      lines.push('```');
      lines.push(Object.entries(info.turn1Hand).map(([n, c]) => `${n}: ${c}`).join(', '));
      lines.push('```');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);

  return lines.join('\n');
}

/**
 * Main CLI handler
 */
function main() {
  const args = process.argv.slice(2);

  if (args.includes('--help') || args.includes('-h')) {
    console.log(`
Seed Discovery Script

Usage:
  npx ts-node scripts/discover-seeds.ts --card <CardName> [--count N]
  npx ts-node scripts/discover-seeds.ts --all-cards [--count N]
  npx ts-node scripts/discover-seeds.ts --generate-reference

Options:
  --card <name>         Find seeds for specific card
  --all-cards           Find seeds for all kingdom cards
  --count <N>           Number of seeds to find per card (default: 1)
  --generate-reference  Generate docs/testing/SEED_REFERENCE.md
  --help, -h            Show this help

Examples:
  npx ts-node scripts/discover-seeds.ts --card Chapel --count 3
  npx ts-node scripts/discover-seeds.ts --generate-reference
`);
    return;
  }

  const countIdx = args.indexOf('--count');
  const count = countIdx >= 0 ? parseInt(args[countIdx + 1]) || 1 : 1;

  if (args.includes('--generate-reference')) {
    console.log('Generating seed reference documentation...');
    const seedMap = findSeedsForAllCards(count);
    const markdown = generateMarkdownReference(seedMap);

    const outPath = path.join(__dirname, '..', 'docs', 'testing', 'SEED_REFERENCE.md');
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, markdown);

    console.log(`\nSaved to: ${outPath}`);
    return;
  }

  if (args.includes('--all-cards')) {
    const seedMap = findSeedsForAllCards(count);
    console.log('\nResults:');
    console.log(JSON.stringify(seedMap, null, 2));
    return;
  }

  const cardIdx = args.indexOf('--card');
  if (cardIdx >= 0 && args[cardIdx + 1]) {
    const cardName = args[cardIdx + 1];
    console.log(`Finding ${count} seed(s) for ${cardName}...`);
    const seeds = findSeedsForCard(cardName, count);

    if (seeds.length === 0) {
      console.log(`No seeds found for ${cardName} (card may not exist or not in 2E)`);
      return;
    }

    console.log('\nResults:');
    for (const info of seeds) {
      console.log(`\nSeed: ${info.seed}`);
      console.log(`Kingdom: ${info.kingdomCards.join(', ')}`);
      console.log(`Hand: ${JSON.stringify(info.turn1Hand)}`);
    }
    return;
  }

  console.log('No valid arguments. Use --help for usage.');
}

main();
